export const PETS = [
  {
    id: 1,
    name: 'Liza',
    species: 'Dog',
    dateOfBirth: '1988-04-03',
    dateOfDeath: '2004-06-23',
    note: 'Very playful one, loves water hoses.',
  },
  {
    id: 2,
    name: 'Kira',
    species: 'Dog',
    dateOfBirth: '2007-06-01',
    dateOfDeath: '2022-05-14',
    note: 'Forever rebel.',
  },
  {
    id: 3,
    name: 'Alex',
    species: 'Dog',
    dateOfBirth: '2013-08-09',
    note: 'Loves petting, will not grow up.',
  },
  {
    id: 4,
    name: 'Odin',
    species: 'Dog',
    dateOfBirth: '2017-07-04',
    note: 'A stick rather amazes him, than a petting hand. Favorite word: "walkies?"',
  },
  {
    id: 5,
    name: 'Pityuka',
    species: 'Cat',
    dateOfBirth: 'unknown',
    note: 'The cat reincarnation of Buddha.',
  },
  {
    id: 6,
    name: 'Szotyika',
    species: 'Cat',
    dateOfBirth: 'unknown',
    note: "She's quite untrustful at first, but with a little treat, she softens up.",
  },
];
